name: C++ Runtime Benchmark
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Google C++ Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get install libblas-dev libhdf5-dev libjack-dev

      - name: Cache Benchmark library
        uses: actions/cache@v4
        with:
          path: benchmarks
          key: ${{ runner.os }}-googlebenchmark-v1.5.0

      - name: Build
        run: |
          autoreconf -vif
          mkdir build && cd build
          ../configure
          make

      - name: Tests
        run: cd build && make tests

      - name: Run benchmark
        run: cd build && make bench-json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: build/benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: benchmarks
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
