name: C++ Runtime Benchmark
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Google C++ Benchmark
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache Benchmark library
        uses: actions/cache@v4
        with:
          path: benchmarks
          key: ${{ runner.os }}-googlebenchmark-v1.5.0
      - name: Run benchmark
        run: make benchmarks

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: examples/cpp/benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
